# apiVersion: v1
# kind: Service
# metadata:
#   name: login-ms
#   labels:
#     app: login-ms
# spec:
#   ports:
#   - port: 5000
#     targetPort: http-server
#   selector:
#     app: login-ms
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: login-ms
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    role: login-ms

# apiVersion: v1
# kind: Service
# metadata:
#   name: login-ms
#   labels:
#     app: login-ms
# spec:
#   ports:
#   - port: 5000
#     targetPort: http-server
#   selector:
#     app: login-ms
#   type: LoadBalancer