apiVersion: v1
kind: Service
metadata:
  name: redbicicletas
  labels:
    app: redbicicletas
spec:
  ports:
  - port: 4000
    targetPort: http-server
  selector:
    app: redbicicletas
  type: LoadBalancer